CREATE PROCEDURE [dbo].[ConfigureFullTextSearchCatalogIfRequired]
AS
BEGIN

	SET ARITHABORT, NOCOUNT, XACT_ABORT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	BEGIN TRY

	IF NOT EXISTS (SELECT 1 FROM sys.fulltext_catalogs WHERE [Name] = 'ArchivialFtsCatalog')
	BEGIN
		CREATE FULLTEXT CATALOG ArchivialFtsCatalog AS DEFAULT
	END

	END TRY
	BEGIN CATCH

		;THROW

	END CATCH

	RETURN 0

END